export const about = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'About Me',
  headLine: 'Je suis Kenny Callegari',
  description: 'Oui oui c\'est bien moi je Suis Kenny Callegari et j\'ai 26 ans, ça fait vieux quand même',
  buttonLabel: 'Contactez moi',
  imgStart: false,
  img: require('../../images/about.svg'),
  alt: 'oui oui',
  dark: true,
  darkText: false,
  primary: true,
};

export const porfolio = {
  id: 'portfolio',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Mon Portfolio',
  headLine: 'Je vous présente mes projets',
  description: 'Effectivement j\'ai pas fait grand chose mais au moins j\'ai fait ça',
  buttonLabel: 'oui oui',
  imgStart: true,
  img: require('../../images/portfolio.svg'),
  alt: 'portofolio',
  primary: false,
};

export const contactMe = {
  id: 'contactMe',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Contactez moi',
  headLine: 'Skusku',
  description: 'Effectivement vous pouvez me contacter merci beaucoup oui oui',
  buttonLabel: 'oui',
  imgStart: true,
  img: require('../../images/portfolio.svg'),
  lottie: true,
  alt: 'contactMe',
  primary: false,
};